services:
  api:
    build: .
    container_name: bus_api
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - redis
    ports:
      - "8080:8080"
  redis:
    image: redis:8.0
    container_name: redis-bus
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes", "--requirepass", "12345"]
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  redis_data: